FROM mcr.microsoft.com/dotnet/sdk:8.0 as builder
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        clang \
        zlib1g-dev

COPY /src/* ./

RUN dotnet publish -r linux-x64 -c Release --ucr --sc -o out

FROM gcr.io/distroless/base-debian12:latest
WORKDIR /app

COPY --from=builder --chmod=+x /app/out/vpm-build-repository .

ENTRYPOINT [ "/app/vpm-build-repository" ]
